// <auto-generated />
using System;
using CleanArchitecture.WebApiFramework.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArchitecture.WebApiFramework.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FrameworkDbContext))]
    [Migration("20210728185354_AddNombreConstraintClaveUnicaRegistroSistema")]
    partial class AddNombreConstraintClaveUnicaRegistroSistema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArchitecture.WebApiFramework.Domain.Entities.ClaveRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clave1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Clave2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Clave3")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Clave4")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Clave5")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValorPredeterminado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresPosibles")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Clave1", "Clave2", "Clave3", "Clave4", "Clave5")
                        .IsUnique()
                        .HasName("IX_CLAVE_UNICA_REGISTRO_SISTEMA")
                        .HasFilter("[Clave1] IS NOT NULL AND [Clave2] IS NOT NULL AND [Clave3] IS NOT NULL AND [Clave4] IS NOT NULL AND [Clave5] IS NOT NULL");

                    b.ToTable("ClavesRegistroSistema");
                });

            modelBuilder.Entity("CleanArchitecture.WebApiFramework.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
